server.port=8081
#server.servlet.context-path=/api

spring.data.mongodb.uri=mongodb://localhost:27017/drug_reporting_portal
spring.data.mongodb.database=drug_reporting_portal

spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=20bcs099@nith.ac.in
spring.mail.password=arykphnipnxzgnno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
