server.port=8080
#server.servlet.context-path=/api

spring.data.mongodb.uri=mongodb://localhost:27017/drug_reporting_portal
spring.data.mongodb.database=drug_reporting_portal

spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=DEBUG

twilio.accountSid=dummy
twilio.authToken=dummy
twilio.whatsappFrom=whatsapp:+14155238886
